name = "sunnyvale-onions-and-honey"
compatibility_date = "2026-03-01"
compatibility_flags = ["nodejs_compat"]
main = ".open-next/worker.js"

[vars]
ACTIVE_PSP = "aci"
EV_APP_ID = "app_83ec49c3a3f6"
ACI_ENTITY_ID = "8a8294174b7ecb28014b9699220015ca"
ACI_RELAY_DOMAIN = "eu-prod.oppwa.com.relay.evervault.app"
STRIPE_RELAY_DOMAIN = "api.stripe.com.relay.evervault.app"
ALLOWED_ORIGINS = "http://localhost:3000,https://sunnyvale-oh.pages.dev"

[[kv_namespaces]]
binding = "SESSIONS"
id = "68a64261f4e3496ea8644dce1a25e1c3"